### PR TITLE
Retrieving the metadata from local json files rather than using the C…

### PR DESCRIPTION
**Pull request by mbucknell**
…SW service. I made no changes to the way the records are stored and instead modified the reader to process a json file rather than the CSW XML.

The json is organized so that there is a parent.json file containing the information that the app needs to initialize. Each derivative has two files. For example for Days With Tmax Above, there is a days_with_tmax_above.json and days_with_tmax_above_scenarios.json. This mimics the separate calls to the CSW for these pieces of information. I have only created files for Days With Tmax Above and Days with Tmin Below. The rest will follow once the format has been approved.

The files are read using the new files MetadataRecordsStore and MetadataRecordsReader. I have left in the CSWGetRecordsStore and CSWGetRecordsReader even though they are no longer included in the app. I thought it might be valuable to have them hang around for awhile.

### CODE REVIEW

**Comment by mbucknell** [comment]
@dblodgett-usgs , could review and approve the json file structure?

**Comment by dblodgett-usgs** [comment]
:+1:

**Comment by jiwalker-usgs** [comment]
I like it, very clean and the JSON looks right to me.

**Comment by jiwalker-usgs** [comment]
:shipit:

**Comment by mbucknell** [comment]
Added the rest of the derivative and scenarios json files. @dblodgett. The WMS services are using cida-eros-derivativeprod.er.usgs.gov:8080 for the WMS services. They all seem to work except if Growing Degree Days is chosen with a scenario of B1

**Comment by dblodgett** [comment]
I think you entered the wrong pseudo name in error.

**Comment by mbucknell** [comment]
@dblodgett-usgs , see comment above. Got the wrong dblodgett

**Pull request merged**
